apiVersion: v1
kind: Namespace
metadata:
  name: mesh-native
  annotations:
    configsync.gke.io/cluster-name-selector: config-sync-mono-cluster
  labels:
    #istio-injection: enabled
    # istio.io/rev: asm-182-2
    admission.gatekeeper.sh/ignore: "true"
