apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: cloudops-logging-gsa@xpo-ltl-sbox.iam.gserviceaccount.com
  name: default
  namespace: configconnector-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cnrm.cloud.google.com/operator-system: 'true'
  name: configconnector-operator
  namespace: configconnector-operator-system