apiVersion: v1
kind: Service
metadata:
  labels:
    cnrm.cloud.google.com/operator-system: 'true'
  name: configconnector-operator-service
  namespace: configconnector-operator-system
spec:
  ports:
  - name: controller-manager
    port: 443
  selector:
    cnrm.cloud.google.com/component: configconnector-operator
    cnrm.cloud.google.com/operator-system: 'true'